version: '3'

services:
  open_notebook_full:
    build:
      context: .
      dockerfile: Dockerfile_full
    ports:
      - "8080:8502"
    volumes:
      - ./.docker_data/data:/app/data
      - ./docker2.env:/app/.env
      - ./google-credentials.json:/app/google-credentials.json
